canonical: https://gematik.de/fhir/erpchrg
fhirVersion: 4.0.1
applyExtensionMetadataToRoot: false
id: de.gematik.eflow-chargeitem
name: gemIG_eRp_ChargeItem
title: "Abrechnungsinformationen des E-Rezepte für PKV-Versicherte"
status: draft # draft | active | retired | unknown
version: "1.1.0-draft"
copyrightYear: 2026+
releaseLabel: ci-build # ci-build, ballot, release
jurisdiction: urn:iso:std:iso:3166#DE "Germany" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: gematik GmbH
  url: https://gematik.de
  email: erp-umsetzung@gematik.de

dependencies:
  de.basisprofil.r4: 1.5.2
  de.gematik.ti: 1.2.0

menu:
  Start: index.html
  Fachlichkeit:
    Überblick: menu-fachlichkeit-ueberblick.html
    Szenarien: menu-fachlichkeit-szenario-pkv.html
    Anwendungsfälle: menu-fachlichkeit-anwendungsfaelle.html
  Technische Umsetzung:
    Systemüberblick: menu-technische-umsetzung-systemueberblick.html
    Technische Anwendungsfälle: menu-technische-umsetzung-anwendungsfaelle.html
    Verarbeitungsregeln: menu-technische-umsetzung-verarbeitungsregeln.html
  Schnittstellen:
    Generelle Prinzipien: menu-schnittstellen-generelle-prinzipien.html
    Datenschutz und Sicherheit: menu-schnittstellen-datenschutz-und-sicherheit.html
    Query API: query-api.html
    Operation API: operation-api.html
    Additional APIs: menu-schnittstellen-additional-api.html
  Anhänge:
    Referenzen: referenced.html
    Downloads: downloads.html
    # OpenAPI: erp-chrg-openapi.html
    Release Notes: release-notes.html
    Steckbriefe: spec-sheet.html
    # Versionsvergleiche: comparisons.html
    Lizenz: license.html
  FHIR-Artefakte: artifacts.html

pages:
  index.md:
    title: "Implementation Guide E-Rezept-Fachdienst"
  menu-fachlichkeit-ueberblick.md:
    title: "Überblick zur Verordnung und Belieferung von Arzneimitteln"
    menu-fachlichkeit-szenario-pkv.md:
      title: "Szenarien für den PKV-Workflow"
    menu-fachlichkeit-anwendungsfaelle.md:
      title: "Anwendungsfälle für den Abrechnungsinformationen des E-Rezepts für PKV-Versicherte"
  menu-technische-umsetzung-systemueberblick.md:
    title: "Systemüberblick"
    menu-technische-umsetzung-anwendungsfaelle.md:
      title: "Technische Anwendungsfälle"
    menu-technische-umsetzung-verarbeitungsregeln.md:
      title: "Verarbeitungsregeln für den E-Rezept-Fachdienst"
  menu-schnittstellen-generelle-prinzipien.md:
    title: "Generelle Prinzipien"
  menu-schnittstellen-datenschutz-und-sicherheit.md:
    title: "Datenschutz und Sicherheit"
  query-api.md:
    title: "Query API"
    query-api-chargeitem.md:
      title: "Query API: ChargeItem"
    query-api-consent.md:
      title: "Query API: Consent"
    query-api-communication.md:
      title: "Query API: Communication"
    query-api-task.md:
      title: "Query API: Task"
  operation-api.md:
    title: "Operation API"
    op-accept.md:
      title: "Operation: $accept"
    op-activate.md:
      title: "Operation: $activate"
  artifacts.md:
    title: "FHIR-Artefakte"
  menu-schnittstellen-additional-api.md:
    title: "Additional APIs"
  referenced.md:
    title: "Referenzen"
  downloads.md:
    title: "Downloads"
  # erp-openapi.md:
  #   title: "OpenAPI: E-Rezept Produkttypen"
  release-notes.md:
    title: "Release Notes"
  spec-sheet.md:
    title: "Steckbriefe"
  # comparisons.md:
  #   title: "Versionsvergleiche"
  license.md:
    title: "Apache Licence"

parameters:
  path-pages:
    - input/pagecontent
    - input/content
  no-narrative:
    # "StructureDefinition/*" doesn't seem to work anymore
    - StructureDefinition/*
    - Bundle/*
    - OperationOutcome/*
    - Medication/*
    - MedicationRequest/*
    - MedicationDispense/*
    - Parameters/*
    - CapabilityStatement/*
    - Provenance/*
  #autoload-resources: true
