canonical: https://gematik.de/fhir/erp-diga
fhirVersion: 4.0.1
applyExtensionMetadataToRoot: false
id: de.gematik.eflow-diga
name: E-Rezept DiGA #TODO Name muss von Team Polarion vorgegeben werden gemIG...
title: "Verordnungen für Digitale Gesundheitsanwendungen (DiGA)"
status: draft # draft | active | retired | unknown
version: "2.0.0-draft"
copyrightYear: 2026+
releaseLabel: ci-build # ci-build, ballot, release
jurisdiction: urn:iso:std:iso:3166#DE "Germany" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: gematik GmbH
  url: https://gematik.de
  email: erp-umsetzung@gematik.de

dependencies:
  de.basisprofil.r4: 1.5.4
  de.gematik.epa.medication: 1.3.0
  de.gematik.ti: 1.2.0

menu:
  Start: index.html
  Fachlichkeit:
    Überblick: menu-fachlichkeit-ueberblick.html
    Szenarien: menu-fachlichkeit-szenarien.html
    Epic: menu-fachlichkeit-epic.html
    User Stories: menu-fachlichkeit-userstories.html
    Anwendungsfälle: menu-fachlichkeit-anwendungsfaelle.html
  Technische Umsetzung:
    Systemüberblick: menu-technische-umsetzung-systemueberblick.html
    Technische Anwendungsfälle: menu-technische-umsetzung-anwendungsfaelle.html
    Verarbeitungsregeln: menu-technische-umsetzung-verarbeitungsregeln.html
    Datenschutz und Informationssicherheit: menu-datenschutz-und-sicherheit.html
  Schnittstellen:
    Generelle Prinzipien: menu-schnittstellen-generelle-prinzipien.html
    Query API: query-api.html
    Operation API: operation-api.html
    Additional APIs: menu-schnittstellen-additional-api.html
  Anhänge:
    Referenzen: referenced.html
    Downloads: downloads.html
    Release Notes: release-notes.html
    Steckbriefe: spec-sheet.html
    Lizenz: license.html
  FHIR-Artefakte: artifacts.html

pages:
  index.md:
    title: "Implementation Guide elektronische Verordnung von DiGAs"
  menu-fachlichkeit-ueberblick.md:
    title: "Überblick zur Verordnung von DiGAs"
    menu-fachlichkeit-epic.md:
      title: "Epic"
    menu-fachlichkeit-userstories.md:
      title: "User Stories"
    menu-fachlichkeit-szenarien.md:
      title: "Szenarien für den DiGA-Workflow"
      menu-fachlichkeit-szenario-diga.md:
        title: "Szenario: Verordnungen für DiGA"
    menu-fachlichkeit-anwendungsfaelle.md:
      title: "Anwendungsfälle im DiGA-Workflow"
  menu-technische-umsetzung-systemueberblick.md:
    title: "Systemüberblick"
    menu-technische-umsetzung-anwendungsfaelle.md:
      title: "Technische Anwendungsfälle"
    menu-technische-umsetzung-verarbeitungsregeln.md:
      title: "Verarbeitungsregeln"
  menu-schnittstellen-generelle-prinzipien.md:
    title: "Generelle Prinzipien"
  menu-datenschutz-und-sicherheit.md:
    title: "Datenschutz und Informationssicherheit"
  query-api.md:
    title: "Query API"
    query-api-task.md:
      title: "Query API: Task"
    query-api-communication.md:
      title: "Query API: Communication"
      query-api-communication-req-fdv.md:
        title: "Anforderungen an das E-Rezept-FdV für Communication API"
      query-api-communication-req-ktr.md:
        title: "Anforderungen an das Clientsystem des Kostenträgers für Communication API"
    query-api-medicationdispense.md:
      title: "Query API: MedicationDispense"
  operation-api.md:
    title: "Operation API"
    op-create.md:
      title: "Operation: $create"
      op-create-req-client.md:
        title: "Anforderungen an den verordnende Primärsystem für die $create-Operation"
    op-activate.md:
      title: "Operation: $activate"
      op-activate-req-server.md:
        title: "Anforderungen an den E-Rezept-Fachdienst für die $activate-Operation"
    op-accept.md:
      title: "Operation: $accept"
    op-reject.md:
      title: "Operation: $reject"
    op-close.md:
      title: "Operation: $close"
  artifacts.md:
    title: "FHIR-Artefakte"
  menu-schnittstellen-additional-api.md:
    title: "Additional APIs"
    api-add-fhirvzd.md:
      title: "API FHIR-VZD"
  referenced.md:
    title: "Referenzen"
  downloads.md:
    title: "Downloads"
  release-notes.md:
    title: "Release Notes"
  spec-sheet.md:
    title: "Steckbriefe"
  license.md:
    title: "Apache Licence"

parameters:
  path-pages:
    - input/pagecontent
    - input/content
