current: 1.1.0
directory: input
frozen_hash: null
frozen_version: null
migrated_with_version: 0.3.0
name: IG E-Rezept Patientenrechnung
next_req_number: 364
numbering_mode: sequential
prefix: IG
releases:
- 1.1.0
scope: ERP-CHRG-
