canonical: https://gematik.de/fhir/workflow/core
fhirVersion: 4.0.1
applyExtensionMetadataToRoot: false
id: de.gematik.workflow.core
name: E-Rezept Workflow Core #TODO Name muss von Team Polarion vorgegeben werden gemIG...
title: "Implementation Guide E-Rezept-Workflow Core"
status: draft # draft | active | retired | unknown
version: 1.0.0-draft

copyrightYear: 2025+
releaseLabel: ci-build # ci-build, ballot, release
jurisdiction: urn:iso:std:iso:3166#DE "Germany" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: gematik GmbH
  url: https://gematik.de
  email: erp-umsetzung@gematik.de

dependencies:
  de.gematik.ti: 1.2.0
  de.gematik.erezept-workflow.r4: 1.6.1
  de.gematik.epa.medication: 1.3.0
  de.basisprofil.r4: 1.5.4
  de.gematik.terminology: 1.0.8

menu:
  Start: index.html
  Grundlagen:
    Zugriffsprotokollierung: audit-service.html
    Datenschutz und Sicherheit: data-security.html
    FHIR-Validierung: fhir-validate.html
    Loeschfristen: ttl.html
  Schnittstellen:
    Operation API: operation-api.html
  FHIR-Artefakte: artifacts.html

pages:
  index.md:
    title: "Implementation Guide E-Rezept-Workflow Core"
  audit-service.md:
    title: "Zugriffsprotokollierung"
  data-security.md:
    title: "Datenschutz und Sicherheit"
  fhir-validate.md:
    title: "FHIR-Ressource validieren"
  ttl.md:
    title: "Loeschfristen"
  operation-api.md:
    title: "Operation API (moduluebergreifend)"
    op-create.md:
      title: "Operation $create (Task erzeugen)"
    op-activate.md:
      title: "Operation $activate (Task aktivieren)"
    op-abort.md:
      title: "Operation $abort (Task abbrechen)"
  artifacts.md:
    title: "FHIR-Artefakte"

parameters:
  path-pages:
    - input/pagecontent
    - input/content
