canonical: https://gematik.de/fhir/workflow/core
fhirVersion: 4.0.1
id: de.gematik.workflow.core
name: E-Rezept Workflow Core #TODO Name muss von Team Polarion vorgegeben werden gemIG...
title: "Implementation Guide E-Rezept-Workflow Core"
status: draft # draft | active | retired | unknown
version: 1.0.0-draft

copyrightYear: 2025+
releaseLabel: ci-build # ci-build, ballot, release
jurisdiction: urn:iso:std:iso:3166#DE "Germany" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: gematik GmbH
  url: https://gematik.de
  email: erp-umsetzung@gematik.de

dependencies:
  de.gematik.ti: 1.2.0