canonical: https://gematik.de/fhir/workflow-server
fhirVersion: 4.0.1
applyExtensionMetadataToRoot: false
id: de.gematik.workflow.server
name: IG-WF-Server
title: "Workflow Server Spezifikation"
status: draft # draft | active | retired | unknown
version: "1.0.0-draft"
copyrightYear: 2026+
releaseLabel: ci-build # ci-build, ballot, release
jurisdiction: urn:iso:std:iso:3166#DE "Germany" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: gematik GmbH
  url: https://gematik.de
  email: erp-umsetzung@gematik.de

dependencies:
  de.gematik.ti: 1.2.0

menu:
  Start: index.html
  Wegweiser: wegweiser.html
  FHIR-Artefakte: artifacts.html

pages:
  index.md:
    title: "eFlow Server - Startpunkt"
  wegweiser.md:
    title: "Wegweiser und Lesepfade"
  artifacts.md:
    title: "FHIR-Artefakte"
  
parameters:
  path-pages:
    - input/pagecontent
    - input/content