current: 1.0.0
directory: input
frozen_hash: null
frozen_version: null
migrated_with_version: 0.3.0
name: IG Workflow Arzneimittel
next_req_number: 1
numbering_mode: sequential
prefix: IG
releases:
- 1.0.0
scope: WF-RX-
