current: 1.0.0
directory: input
frozen_hash: null
frozen_version: null
migrated_with_version: 0.3.0
name: IG TIFlow Arzneimittel
next_req_number: 332
numbering_mode: sequential
prefix: IG
releases:
- 1.0.0
scope: TIFlow-RX-
